### ISSUE TITLE
Spelling error in docs

### ISSUE THREAD

**Issue by akira-baruah** [OPAE/opae.github.io#2]
The `Hugepage Settings` section of the installation guide is [misspelled](https://github.com/OPAE/opae.github.io/blob/7fbf6dcebc9c7bdbb03317b5408c5f45c1f946e6/_sources/docs/install_guide/installation_guide.md.txt#L233).

**Comment by akira-baruah** [comment]
I'd be happy to push the fix, but it seems like the docs in the this repo are not upstream source (see PR #1).

@luebbers should I hold off on submitting a PR with the fix?

**Comment by luebbers** [comment]
@akira-baruah yes, please. We are working on integrating the documentation sources.
